# Generated by Django 4.1.1 on 2022-09-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rental', models.IntegerField()),
                ('data_with_rollover', models.IntegerField()),
                ('sms_per_day', models.IntegerField()),
                ('local_std_roaming', models.CharField(max_length=15)),
                ('amazon_prime', models.CharField(max_length=10)),
            ],
        ),
    ]
