# Generated by Django 4.1.1 on 2022-09-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_scrapper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
