# Generated by Django 4.1.1 on 2022-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_scrapper_app', '0002_rename_plans_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data_with_rollover',
            field=models.CharField(max_length=5),
        ),
    ]
