# Generated by Django 4.1.1 on 2022-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_scrapper_app', '0003_alter_plan_data_with_rollover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data_with_rollover',
            field=models.CharField(max_length=10),
        ),
    ]
